# configs/environment_config.yaml

# Time Parameters
time:
  step_duration: 5     # Time step duration (minutes)
  max_steps_per_episode: 864 # Steps per episode (3 days)

# Pricing Parameters
pricing:
  eta: 0.5            # Smoothing factor for running average price

# ISO Configuration Reference
iso_config_path: "configs/iso_config.yaml"

# PCSUnit Configuration Reference
pcs_unit_config_path: "configs/pcs_unit_config.yaml"

reward:
  type: 'cost' 
