# configs/iso_config.yaml

# Specifies which ISO implementation to use
type: "HourlyPricingISO"

# Parameters specific to the chosen ISO
parameters:
  # For HourlyPricingISO
  hourly_rates:
    0: 40.0
    1: 40.0
    2: 40.0
    3: 40.0
    4: 40.0
    5: 50.0
    6: 60.0
    7: 60.0
    8: 55.0
    9: 50.0
    10: 50.0
    11: 55.0
    12: 60.0
    13: 60.0
    14: 55.0
    15: 50.0
    16: 50.0
    17: 55.0
    18: 60.0
    19: 60.0
    20: 55.0
    21: 50.0
    22: 45.0
    23: 40.0

  # Example: To use RandomPricingISO, change type and parameters accordingly
  # type: "RandomPricingISO"
  # parameters:
  #   min_price: 40.0
  #   max_price: 60.0
